repos:
- repo: local
  hooks:
    - id: format
      name: format
      entry: cd server && make format
      language: system
      pass_filenames: false
      always_run: true
      verbose: true
      files: ^server/
