repos:
- repo: local
  hooks:
    - id: format server
      name: format server
      entry: cd server && make format
      language: system
      pass_filenames: false
      always_run: true
      verbose: true
      files: ^server/
