AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Whisker RAG Server

Globals:
  Function:
    Timeout: 300

Parameters:
  s3TempBucketName:
    Type: String
    Description: Environment marker for S3_TEMP_BUCKET_NAME
    Default: "whisker-rag"

  supabaseServiceKey:
    Type: String
    Description: Environment marker for SUPABASE_SERVICE_KEY
    Default: "1"

  supabaseUrl:
    Type: String
    Description: Environment marker for SUPABASE_URL
    Default: "1"

  webUrl:
    Type: String
    Description: Environment marker for WEB_URL
    Default: "1"

  knowledgeTableName:
    Type: String
    Description: Environment marker for KNOWLEDGE_TABLE_NAME
    Default: "knowledge"

  ApiKeyTableName:
    Type: String
    Description: Environment marker for API_KEY_TABLE_NAME
    Default: "api_key"
  
  chunkTableName:
    Type: String
    Description: Environment marker for CHUNK_TABLE_NAME
    Default: "chunk"

  taskTableName:
    Type: String
    Description: Environment marker for TASK_TABLE_NAME
    Default: "task"

  tenantTableName:
    Type: String
    Description: Environment marker for TENANT_TABLE_NAME
    Default: "tenant"

  openAIKey:
    Type: String
    Description: Environment marker for OPENAI_API_KEY
    Default: "1"

  dbEngineClassName:
    Type: String
    Description: Environment marker for DB_ENGINE_CLASSNAME
    Default: "SupaBasePlugin"

  fastapiEngineClassName:
    Type: String
    Description: Environment marker for FASTAPI_ENGINE_CLASSNAME
    Default: "FastAPIPlugin"

  taskEngineClassName:
    Type: String
    Description: Environment marker for TASK_ENGINE_CLASSNAME
    Default: "AWSLambdaTaskEnginePlugin"

  whiskerEnv:
    Type: String
    Description: Environment marker for WHISKER_ENV
    Default: "prod"

  sqsQueueUrl:
    Type: String
    Description: Environment marker for SQS_QUEUE_URL
    Default: "1"

  whiskerPluginPath:
    Type: String
    Description: Environment marker for WHISKER_PLUGIN_PATH
    Default: "./supabase_aws_plugin"

Resources:
  WhiskerServer:
    Type: AWS::Serverless::Function
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          WEB_URL: !Ref webUrl
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
          S3_TEMP_BUCKET_NAME: !Ref s3TempBucketName
          SUPABASE_SERVICE_KEY: !Ref supabaseServiceKey
          SUPABASE_URL: !Ref supabaseUrl
          KNOWLEDGE_TABLE_NAME: !Ref knowledgeTableName
          API_KEY_TABLE_NAME: !Ref ApiKeyTableName
          CHUNK_TABLE_NAME: !Ref chunkTableName
          TASK_TABLE_NAME: !Ref taskTableName
          TENANT_TABLE_NAME: !Ref tenantTableName
          OPENAI_API_KEY: !Ref openAIKey
          DB_ENGINE_CLASSNAME: !Ref dbEngineClassName
          FASTAPI_ENGINE_CLASSNAME: !Ref fastapiEngineClassName
          TASK_ENGINE_CLASSNAME: !Ref taskEngineClassName
          SQS_QUEUE_URL: !Ref sqsQueueUrl
          # whisker plugin path
          WHISKER_PLUGIN_PATH: !Ref whiskerPluginPath
          # git env config - using system git from Docker image
          GIT_PYTHON_REFRESH: quiet
          GIT_EXEC_PATH: /usr/bin/git
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
      - Statement:
          - Sid: BedrockInvokePolicy
            Effect: Allow
            Action:
              - bedrock:InvokeModelWithResponseStream
            Resource: '*'
          - Sid: AllObjectActions
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub 'arn:aws:s3:::${s3TempBucketName}/*'
      Tracing: Active
    Metadata:
      DockerContext: server
      Dockerfile: ../docker/Dockerfile.aws.server
      DockerTag: v1

Outputs:
  WhiskerServer:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt WhiskerServer.Arn
  WhiskerFunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt WhiskerServerUrl.FunctionUrl