version = 0.1
[default.build.parameters]
template = "template.yml"

[default.deploy.parameters]
stack_name = "whisker-rag"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = [""]

# dev 环境只需要覆盖特定参数
[preview.deploy.parameters]
stack_name = "whisker-rag-preview"

# prod 环境只需要覆盖特定参数
[prod.deploy.parameters]
stack_name = "whisker-rag-prod"