version = 0.1
[default.build.parameters]
template = "template.yml"

[default.deploy.parameters]
resolve_s3 = true
s3_bucket = "whisker-rag"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true

# dev 环境只需要覆盖特定参数
[preview.deploy.parameters]
stack_name = "whisker-rag-preview"
s3_prefix = "whisker-rag-preview"
image_repositories = ["WhiskerServer=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/server-preview", "TaskFunction=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/task-preview"]

# prod 环境只需要覆盖特定参数
[prod.deploy.parameters]
stack_name = "whisker-rag"
s3_prefix = "whisker-rag"
image_repositories = ["WhiskerServer=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/server", "TaskFunction=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/task"]