version = 0.1
[default.build.parameters]
template = "template_server.yml"

[preview.deploy.parameters]
resolve_s3 = false
s3_bucket = "whisker-rag"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "whisker-rag-server-preview"
s3_prefix = "whisker-rag-preview"
image_repositories = [
  "WhiskerServer=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/server-preview"
]

[prod.deploy.parameters]
resolve_s3 = false
s3_bucket = "whisker-rag"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "whisker-rag-server"
s3_prefix = "whisker-rag"
image_repositories = [
  "WhiskerServer=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/server",
]
