version = 0.1
[default.build.parameters]
template = "template.yml"

[preview.deploy.parameters]
resolve_s3 = false
s3_bucket = "whisker-rag"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "whisker-rag-task-preview"
s3_prefix = "whisker-rag-preview"
image_repositories = [
  "TaskFunction=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/task",
]

[prod.deploy.parameters]
resolve_s3 = false
s3_bucket = "whisker-rag"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
stack_name = "whisker-rag-task"
s3_prefix = "whisker-rag"
image_repositories = [
  "TaskFunction=654654285942.dkr.ecr.ap-northeast-1.amazonaws.com/whisker/task",
]
