name: Deploy SAM app to AWS

on:
  workflow_run:
    workflows: ["server-ci"]
    types: ["completed"]
    branches: ["test"]
  push:
    branches: ["test"]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
      - '.aws/server_samconfig.toml'
      - 'template_server.yml'


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  actions: write

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    environment: Preview
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654285942:role/Github-OIDC
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}

      - name: Print specific variables
        run: |
          echo "Current DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}"
          echo "GitHub actor: ${{ github.actor }}"

      # Build inside Docker containers
      - run: sam build --use-container --template template_server.yml --config-file .aws/server_samconfig.toml

      # Prevent prompts and failure when the stack is unchanged
      - run: |
          sam deploy \
            --no-confirm-changeset \
            --config-env ${{ vars.DEPLOY_ENV}} \
            --no-fail-on-empty-changeset \
            --config-file .aws/server_samconfig.toml \
            --parameter-overrides \
              ParameterKey=supabaseServiceKey,ParameterValue=${{ secrets.SUPABASE_SERVICE_KEY }} \
              ParameterKey=supabaseUrl,ParameterValue=${{ secrets.SUPABASE_URL }} \
              ParameterKey=apiUrl,ParameterValue=${{ vars.API_URL }} \
              ParameterKey=webUrl,ParameterValue=${{ vars.WEB_URL }} \
              ParameterKey=knowledgeTableName,ParameterValue=${{ vars.KNOWLEDGE_TABLE_NAME }} \
              ParameterKey=chunkTableName,ParameterValue=${{ vars.CHUNK_TABLE_NAME }} \
              ParameterKey=taskTableName,ParameterValue=${{ vars.TASK_TABLE_NAME }} \
              ParameterKey=actionTableName,ParameterValue=${{ vars.ACTION_TABLE_NAME }} \
              ParameterKey=tenantTableName,ParameterValue=${{ vars.TENANT_TABLE_NAME }}