# .github/workflows/deploy.yml
name: Deploy SAM app to AWS

on:
  workflow_run:
    workflows: ["server-ci"]
    types: ["completed"]
    branches: ["test"]
  push:
    branches: ["test"]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Preview
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654285942:role/Github-OIDC
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}

      # Build inside Docker containers
      - run: sam build --use-container --config-file .aws/amsconfig.toml

      # Prevent prompts and failure when the stack is unchanged
      - run: |
          sam deploy \
            --no-confirm-changeset \
            --config-env ${{ vars.DEPLOY_ENV}}
            --no-fail-on-empty-changeset \
            --config-file .aws/task.toml \
            --parameter-overrides \
              ParameterKey=SUPABASE_SERVICE_KEY,ParameterValue=${{ secrets.SUPABASE_SERVICE_KEY }} \
              ParameterKey=SUPABASE_URL,ParameterValue=${{ secrets.SUPABASE_URL }} \
              ParameterKey=API_URL,ParameterValue=${{ vars.API_URL }} \
              ParameterKey=AWS_ACCOUNT_ID,ParameterValue=${{ secrets.AWS_ACCOUNT_ID }} \
              ParameterKey=AWS_REGION,ParameterValue=${{ secrets.AWS_REGION }} \
              ParameterKey=WEB_URL,ParameterValue=${{ secrets.WEB_URL }}
