name: Server CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: make install

    # - name: Run type check
    #   run: make type-check

    # - name: Run tests
    #   run: make test