name: Deploy whisker server to AWS

on:
  workflow_run:
    workflows: ["server-ci"]
    types: ["completed"]
    branches: ["test","main","preview","test/*","preview/*"]
  push:
    branches: ["test","main","preview","test/*","preview/*"]
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yml'
      - '.aws/server_samconfig.toml'
      - 'template_server.yml'
      - 'docker/Dockerfile.aws.server'
  pull_request:
    branches: ["test","main","preview","test/*","preview/*"]
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yml'
      - '.aws/server_samconfig.toml'
      - 'template_server.yml'
      - 'docker/Dockerfile.aws.server'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  actions: write

env:
  NODE_VERSION: '18'
  PACKAGE_NAME: '@petercat/whiskerrag-client'

jobs:
  determine-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }}
      npm_tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
    steps:
      - name: Determine environment
        id: env
        run: |
          echo "Environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }}"
          echo "NPM tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}"

  server-deploy:
    needs: determine-env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.environment }}
    env:
      ENVIRONMENT: ${{ needs.determine-env.outputs.environment }}
    strategy:
      fail-fast: true
    outputs:
      api_url: ${{ steps.get_api_url.outputs.api_url }}
    steps:
      - name: Print specific variables
        run: |
          echo "Current github.ref : ${{ github.ref }}"
          echo "Deploying to ${{ env.ENVIRONMENT }}"
          echo "Current AWS_REGION: ${{ vars.AWS_REGION }}"
          echo "Current WHISKER_ENV: ${{ vars.WHISKER_ENV }}"
          echo "GitHub actor: ${{ github.actor }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654285942:role/Github-OIDC
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}

      # Build inside Docker containers
      - run: sam build --use-container --template template_server.yml --config-file .aws/server_samconfig.toml

      # Prevent prompts and failure when the stack is unchanged
      - run: |
          sam deploy \
            --no-confirm-changeset \
            --config-env ${{ vars.WHISKER_ENV}} \
            --no-fail-on-empty-changeset \
            --config-file .aws/server_samconfig.toml \
            --parameter-overrides \
              ParameterKey=supabaseServiceKey,ParameterValue=${{ secrets.SUPABASE_SERVICE_KEY }} \
              ParameterKey=supabaseUrl,ParameterValue=${{ secrets.SUPABASE_URL }} \
              ParameterKey=s3TempBucketName,ParameterValue=${{ vars.S3_TEMP_BUCKET_NAME }} \
              ParameterKey=webUrl,ParameterValue=${{ vars.WEB_URL }} \
              ParameterKey=knowledgeTableName,ParameterValue=${{ vars.KNOWLEDGE_TABLE_NAME }} \
              ParameterKey=chunkTableName,ParameterValue=${{ vars.CHUNK_TABLE_NAME }} \
              ParameterKey=taskTableName,ParameterValue=${{ vars.TASK_TABLE_NAME }} \
              ParameterKey=actionTableName,ParameterValue=${{ vars.ACTION_TABLE_NAME }} \
              ParameterKey=tenantTableName,ParameterValue=${{ vars.TENANT_TABLE_NAME }} \
              ParameterKey=openAIKey,ParameterValue=${{ secrets.OPENAI_API_KEY }} \
              ParameterKey=dbEngineClassName,ParameterValue=${{ vars.DB_ENGINE_CLASSNAME }} \
              ParameterKey=taskEngineClassName,ParameterValue=${{ vars.TASK_ENGINE_CLASSNAME }} \
              ParameterKey=whiskerEnv,ParameterValue=${{ vars.WHISKER_ENV }} \
              ParameterKey=sqsQueueUrl,ParameterValue=${{ vars.SQS_QUEUE_URL }} \

      - name: Get API URL
        id: get_api_url
        run: |
          if [ "${{ needs.determine-env.outputs.environment }}" = "Production" ]; then
            CONFIG_ENV="prod"
          else
            CONFIG_ENV="preview"
          fi
          
          STACK_NAME=$(grep "stack_name" .aws/server_samconfig.toml | grep "${CONFIG_ENV}" -A 1 | tail -n 1 | cut -d'"' -f2)
          
          echo "Environment: ${{ needs.determine-env.outputs.environment }}"
          echo "Config Environment: ${CONFIG_ENV}"
          echo "Stack name: ${STACK_NAME}"
          
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name "${STACK_NAME}" \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
            --output text)
          
          echo "API URL: ${API_URL}"
          echo "api_url=${API_URL}" >> $GITHUB_OUTPUT

  generate-client:
    needs: [determine-env, server-deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install swagger-typescript-api
        run: npm install -g swagger-typescript-api

      - name: Generate and Publish Client
        run: |
          ./scripts/generate-client.sh \
            --publish \
            --NPM_TOKEN="${{ secrets.NPM_TOKEN }}" \
            --ENVIRONMENT="${{ needs.determine-env.outputs.environment }}" \
            --API_URL="${{ needs.server-deploy.outputs.api_url }}"
